/**
 * Build the CM6 editor bundle for the mobile WebView.
 *
 * 1. Bundles cm-entry.ts + all CM6 extensions into JS via esbuild
 * 2. Reads editor.html template
 * 3. Inlines JS into the HTML
 * 4. Exports as a TypeScript module: `export const EDITOR_HTML = "..."`;
 *
 * Usage from React Native:
 *   import { EDITOR_HTML } from './editorBundle';
 *   <WebView source={{ html: EDITOR_HTML }} />
 */

import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const igneRoot = resolve(root, '../..');
const editorDir = resolve(root, 'sources', 'editor');

/**
 * esbuild plugin to stub Tauri and other desktop-only modules.
 */
const stubTauriPlugin = {
  name: 'stub-tauri',
  setup(build) {
    build.onResolve({ filter: /^@tauri-apps\// }, (args) => ({
      path: args.path,
      namespace: 'tauri-stub',
    }));
    build.onLoad({ filter: /.*/, namespace: 'tauri-stub' }, () => ({
      contents: 'export const invoke = () => Promise.resolve(); export const convertFileSrc = (s) => s; export default {};',
      loader: 'js',
    }));

    build.onResolve({ filter: /\/utils\/logger$/ }, (args) => ({
      path: args.path,
      namespace: 'logger-stub',
    }));
    build.onLoad({ filter: /.*/, namespace: 'logger-stub' }, () => ({
      contents: `
        const noop = () => {};
        export const logger = {
          debug: noop, info: noop,
          warn: (...args) => console.warn('[igne]', ...args),
          error: (...args) => console.error('[igne]', ...args),
          isDebug: () => false,
        };
      `,
      loader: 'js',
    }));

    build.onResolve({ filter: /^katex$/ }, (args) => ({
      path: args.path,
      namespace: 'katex-stub',
    }));
    build.onLoad({ filter: /.*/, namespace: 'katex-stub' }, () => ({
      contents: `export default { renderToString: (tex) => '<span class="cm-math-fallback">$' + tex + '$</span>' };`,
      loader: 'js',
    }));

    build.onResolve({ filter: /^mermaid$/ }, (args) => ({
      path: args.path,
      namespace: 'mermaid-stub',
    }));
    build.onLoad({ filter: /.*/, namespace: 'mermaid-stub' }, () => ({
      contents: `export default { initialize: () => {}, render: () => Promise.resolve({ svg: '<svg></svg>' }) };`,
      loader: 'js',
    }));
  },
};

async function build() {
  console.log('Building CM6 editor bundle...');
  const isProduction = process.argv.includes('--production');

  // Step 1: Bundle CM6
  const result = await esbuild.build({
    entryPoints: [resolve(editorDir, 'cm-entry.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    target: ['safari14'],
    minify: isProduction,
    sourcemap: false,
    nodePaths: [resolve(igneRoot, 'node_modules')],
    plugins: [stubTauriPlugin],
    define: {
      'process.env.NODE_ENV': isProduction ? '"production"' : '"development"',
      'import.meta.env': '{}',
      'import.meta.env.DEV': 'true',
    },
    logLevel: 'info',
  });

  if (result.errors.length > 0) {
    console.error('Build errors:', result.errors);
    process.exit(1);
  }

  const jsBundle = result.outputFiles[0].text;

  // Step 2: Read HTML template and inline JS
  const htmlTemplate = readFileSync(resolve(editorDir, 'editor.html'), 'utf-8');
  const fullHtml = htmlTemplate.replace(
    '<script src="cm-bundle.js"></script>',
    `<script>\n${jsBundle}\n</script>`
  );

  // Step 3: Write TS module
  const tsModule = `// AUTO-GENERATED by scripts/build-editor.mjs — do not edit\nexport const EDITOR_HTML = ${JSON.stringify(fullHtml)};\n`;
  writeFileSync(resolve(editorDir, 'editorBundle.ts'), tsModule);

  const sizeKB = Math.round(fullHtml.length / 1024);
  console.log(`Generated sources/editor/editorBundle.ts (${sizeKB} KB${isProduction ? ', minified' : ''})`);
}

build().catch((err) => {
  console.error('Build failed:', err);
  process.exit(1);
});
